name: redstone_rethinkdb
version: 0.0.1
author: Cristian Garcia <cgarcia.e88@gmail.com>
description: MVC Plugin for Redstone
homepage: https://github.com/redstone-dart/redstone-mvc-plugin
environment:
  sdk: '>=1.9.1'
documentation: https://github.com/redstone-dart/redstone-mvc-plugin
dependencies:
  redstone: '>=0.5.0 <0.6.0'
  rethinkdb_driver: any
  redstone_mapper: any
  connection_pool: any
