name: redstone_rethinkdb
version: 0.1.0-beta.1+1
author: Cristian Garcia <cgarcia.e88@gmail.com>
description: MVC Plugin for Redstone
homepage: https://github.com/redstone-dart/redstone-mvc-plugin
environment:
  sdk: '>=1.9.1'
documentation: https://github.com/redstone-dart/redstone-mvc-plugin
dependencies:
  redstone: '>=0.6.0-beta.1+1 <0.7.0'
  redstone_mapper: '>=0.2.0-beta.1 <0.3.0'
  rethinkdb_driver: '>=2.0.1+1 <3.0.0'
  connection_pool: '>=0.1.0+2 < 0.2.0'
