name: redstone_rethinkdb
version: 0.0.191
author: Cristian Garcia <cgarcia.e88@gmail.com>
description: RethinkDB Plugin for Redstone
homepage: https://github.com/redstone-dart/redstone_rethinkdb
environment:
  sdk: '>=1.9.1'
documentation: https://github.com/redstone-dart/redstone_rethinkdb
dependencies:
  redstone: '>=0.5.0 <0.6.0'
  rethinkdb_driver: ^2.0.1+1
  redstone_mapper: ^0.1.13
  connection_pool: ^0.1.0+2
